Repository cloudera-labs/cldr-runner, pull requests merged in 2023-10, with the labels that each got.

#64 Update ansible-core to handle point releases
  base/execution-environment.yml
Labels: bug

#62 Update freeipa.ansible_freeipa collection version
  base/requirements.yml
Labels: enhancement

#65 Pin Cloudera collections (cloud, cluster, exe)
  README.md
  base/requirements.yml
Labels: enhancement, validated
